development:
  adapter: postgresql
  encoding: unicode
  database: tps_development
  host: localhost
  pool: 5
  username: tps_development
  password: tps_development

test:
  adapter: postgresql
  encoding: unicode
  database: tps_test
  host: localhost
  pool: 5
  username: tps_test
  password: tps_test
